<a href="https://colab.research.google.com/github/Aman489-art/Emilia/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [150]:
import numpy as np

In [151]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [152]:
a[0]

np.int64(1)

In [153]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [154]:
a[:3]

array([10,  2,  3])

In [155]:
a.ndim #number of dimensions

1

In [156]:
a.shape #shape of an array

(6,)

In [157]:
a.dtype #data type

dtype('int64')

How to create a basic array

In [158]:
np.zeros(2) #an array full of zeros

array([0., 0.])

In [159]:
np.ones(2) #an array full of ones

array([1., 1.])

In [160]:
np.empty(5) # Create an empty array with 2 elements

array([4.94e-323, 4.94e-323, 1.98e-322, 2.47e-322, 2.96e-322])

In [161]:
#create an array with a range of elements:
np.arange(4)

array([0, 1, 2, 3])

In [162]:
#an array that contains a range of evenly spaced intervals.
#To do this, you will specify the first number, last number, and the step size
np.arange(2, 9, 2)


array([2, 4, 6, 8])

In [163]:
# alternate to create an array with values that are spaced linearly in a specified interval
np.linspace(0, 10, num=5)# num=5 is the number of elements

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [164]:
#to explicitly specify which data type you want using the dtype keyword

x = np.ones(2, dtype=np.int16)
x


array([1, 1], dtype=int16)

Adding, removing, and sorting elements

In [165]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [166]:
np.sort(arr)# sort the numbers in ascending order

array([1, 2, 3, 4, 5, 6, 7, 8])

In [167]:
#argsort, which is an indirect sort along a specified axis,

np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

for example:
Original array:
Index: 0 1 2
Value: 30, 10, 20

Sorted array hota:
10 → index 1
20 → index 2
30 → index 0

Isliye output: [1, 2, 0]

**lEXSORT**

In [168]:
#lexsort, which is an indirect stable sort on multiple keys,

a = [1, 5, 1, 4, 3, 4, 4]  # First sequence

b = [9, 4, 0, 4, 0, 2, 1]  # Second sequence

ind = np.lexsort((b, a))  # Sort by `a`, then by `b`
ind
[(a[i], b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

a = primary

b = secondary

STEP 1 -  first sort primary key

| Value | Indexes |
| ----- | ------- |
| 1     | 0, 2    |
| 3     | 4       |
| 4     | 3, 5, 6 |
| 5     | 1       |

[0, 2, 4, 3, 5, 6, 1]


STEP 2 - SORT SAME A GROUPS ACCORDING TO B GROUPS

| Index | a | b |
| ----- | - | - |
| 0     | 1 | 9 |
| 2     | 1 | 0 |
| 3     | 4 | 4 |
| 5     | 4 | 2 |
| 6     | 4 | 1 |


FINAL:
[2, 0, 4, 6, 5, 3, 1]

STEP 3 :
[(a[i], b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]





# SearchSorted

Find indices where elements should be inserted to maintain order.



In [169]:
a = np.array([10,10,40,50,60])
np.searchsorted(a, 30, side='right')

np.int64(2)

# Partition

np.partition() rearranges the elements of an array so that:

the kth smallest element is placed in its correct position (as it would appear in a fully sorted array)

all smaller elements come before it

all larger elements come after it

but the left and right parts are not fully sorted
(only separated)

In [170]:
a = np.array([7, 1, 5, 3, 9, 2])
np.partition(a, 2)


array([1, 2, 3, 5, 7, 9])

In [171]:
np.partition(a, 2, axis=-1, kind='introselect', order=None)


array([1, 2, 3, 5, 7, 9])

# a → the array

# kth → which position to fix

# axis → direction of partition (for multi-dimensional arrays)
**axis=0** → column-wise

**axis=1** → row-wise

**axis=-1** (default) → last axis

# kind='introselect'`
Algorithm used internally.

# order
Used only for structured arrays (arrays with named fields).
Normally you keep it None.

In [172]:
# too add arrays

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [173]:
#to delete any entry from an array

a = np.array([10, 20, 30, 40])
new_a = np.delete(a,2)
new_a

array([10, 20, 40])

In [174]:
a.ndim #To find the number of dimensions of the array,

1

In [175]:
#To find the total number of elements in the array
a.size

4

In [176]:
#to find the shape of your array
a.shape

(4,)

In [177]:
#to reshape an array
a = np.arange(6)
b = a.reshape(3,2) #3 rows ad 2 columns size should be same
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [178]:
x = np.reshape(a, (1, 6), order='C')
x

array([[0, 1, 2, 3, 4, 5]])

| Order   | Meaning       | Filling style      |
| ------- | ------------- | ------------------ |
| **'C'** | C-style       | Row-wise (default) |
| **'F'** | Fortran-style | Column-wise        |


# convert a 1D array into a 2D array

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [179]:

#np.newaixs

a = np.array([1, 2, 3, 4, 5, 6])
a.shape

#to add new axis
a2 = a[np.newaxis, :]
a2.shape
#to convert 1d array in a row vector
ro_vector = a[np.newaxis, :]
ro_vector.shape
#to convert 1d array into column vector
col_vector = a[:, np.newaxis]
col_vector.shape



(6, 1)

In [180]:
#np.expand_dims
#add an axis at index position 1
b = np.expand_dims(a, axis=1)
b


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [181]:
#add an axis at index position 0
b = np.expand_dims(a, axis=0)
b


array([[1, 2, 3, 4, 5, 6]])

# Indexing and Slicing


In [182]:
a
a[0:2]
a[0:]

array([1, 2, 3, 4, 5, 6])

In [183]:
#print all of the values in the array that are less than 5
a[a <5]
a[(a>2) & (a<5)]

array([3, 4])

#create an array from existing data

In [184]:
a
#create a new array from a section of your array any time by specifying where you want to slice your array
new_ar = a[2:5]
new_ar

array([3, 4, 5])

In [185]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

#stack them vertically with vstack
np.vstack((a1, a2))
#stack them horizontally with hstack
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [186]:
x = np.arange(25).reshape(5,5)
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [187]:
#split this array into three equally shaped arrays
np.hsplit(x, 5)

[array([[ 0],
        [ 5],
        [10],
        [15],
        [20]]),
 array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [188]:
 #view method to create a new array object that looks at the same data as the original array (a shallow copy)
#copy method will make a complete copy of the array and its data (a deep copy).

# Basic Operations

In [189]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [190]:
data - ones

array([0, 1])

In [191]:
data * data

array([1, 4])

In [192]:
data / data

array([1., 1.])

In [193]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [194]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [195]:
b.sum(axis=1)

array([2, 4])

In [196]:
a.max()

np.int64(4)

In [197]:
a.min()

np.int64(1)

In [198]:
a.sum()

np.int64(10)

In [199]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones = np.array([[1, 1], [1, 1],[1,1]])
data+ones


array([[2, 3],
       [4, 5],
       [6, 7]])

In [200]:
data*ones

array([[1, 2],
       [3, 4],
       [5, 6]])

In [201]:
np.ones((3, 2))
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Generating random numbers

In [202]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4))

array([[2, 2, 1, 4],
       [0, 2, 4, 4]])

In [203]:
#get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)


[11 12 13 14 15 16 17 18 19 20]


In [204]:
#to get return value as an index

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [205]:
#to get the frequency count of the unique values
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [206]:
#To find the unique rows, specify axis=0 and for columns, specify axis=1

In [207]:
#reshape
a_s = a.reshape(5,3)
a_s

array([[11, 11, 12],
       [13, 14, 15],
       [16, 17, 12],
       [13, 11, 14],
       [18, 19, 20]])

In [208]:
#to transpose
a_s.transpose()

array([[11, 13, 16, 13, 18],
       [11, 14, 17, 11, 19],
       [12, 15, 12, 14, 20]])

In [209]:
#alternate
a_s.T

array([[11, 13, 16, 13, 18],
       [11, 14, 17, 11, 19],
       [12, 15, 12, 14, 20]])

In [210]:
#REVERSE AN ARRAY
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
rev_arr = np.flip(arr)
rev_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [211]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
rev_arr_2d = np.flip(arr_2d)
rev_arr_2d

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [212]:
#reverse row , axis = 0
#reverse column, axis = 1

In [213]:
#There are two popular ways to flatten an array: .flatten() and .ravel()
#ravel does not create a copy, it’s memory efficient
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

When you use flatten, changes to your new array won’t change the parent array.

But when you use ravel, the changes you make to the new array will affect the parent array.


#save and load NumPy objects

In [214]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)

In [215]:
#You can use np.load() to reconstruct your array
b = np.load('filename.npy')
print(b)

[1 2 3 4 5 6]


In [216]:
#You can save a NumPy array as a plain text file like a .csv or .txt file with np.savetxt
np.savetxt('new_file.csv', a)

In [217]:
#You can quickly and easily load your saved text file using loadtxt()
np.loadtxt('new_file.csv')


array([1., 2., 3., 4., 5., 6.])

In [218]:
#boolean masking
a[a>3]

array([4, 5, 6])

In [219]:
#fancy indexing
a[[0,2,5]]

array([1, 3, 6])

In [220]:
#axis wise aggregations
np.sum(arr, axis=0)
np.mean(arr, axis=0)


np.float64(4.5)

In [221]:
#dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

np.int64(32)

In [222]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [224]:
#matrix multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A @ B

array([[19, 22],
       [43, 50]])

In [225]:
# inverse

np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [226]:
#determinant
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [229]:
#Eigenvalues & Eigenvectors
vals, vecs = np.linalg.eig(A)

In [230]:
#Vector/Matrix Length

np.linalg.norm(A)

np.float64(5.477225575051661)

In [231]:
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])